apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-project
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: nginx-warehouse-warehouse
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitopsRepo
        value: https://github.com/martinvasseur-lab/kargo-project.git
      - name: imageRepo
        value: ghcr.io/martinvasseur-lab/kargo-project
      - name: imageTag
        value: 1.0.1
      - name: srcPath
        value: ./src
      - name: outPath
        value: ./out
      - name: targetBranch
        value: stage/${{ ctx.stage }}
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitopsRepo }}
          checkout:
          - branch: main
            path: ${{ vars.srcPath }}
          - branch: stage/${{ ctx.stage }}
            create: true
            path: ${{ vars.outPath }}
      - uses: git-clear
        config:
          path: ${{ vars.outPath }}
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ${{ vars.srcPath }}/base
          images:
          - image: ${{ vars.imageRepo }}
            tag: ${{ vars.imageTag }}
      - uses: kustomize-build
        config:
          path: ${{ vars.srcPath }}/env
          outPath: ${{ vars.outPath }}/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ${{ vars.outPath }}
          message: ${{ outputs['update-image'].commitMessage }}
      - uses: git-push
        config:
          path: ${{ vars.outPath }}
          branch: ${{ vars.targetBranch }}
      - uses: argocd-update
        config:
          apps:
          - name: kargo-demo-${{ ctx.stage }}
            sources:
            - repoURL: ${{ vars.gitopsRepo }}
              desiredRevision: ${{ outputs.commit.commit }}